### ISSUE TITLE
Empty svg attribute?

### ISSUE THREAD

**Issue by kentcdodds** [jackyho112/react-html-attributes#1]
I'm unsure what [this](https://github.com/jackyho112/react-html-attributes/blob/58cc42212b3656e143d3ae5bde1cc22017573e8b/src/react-html-attributes.json#L392) is. Could you explain that a little?

**Comment by jackyho112** [comment]
That's definitely a bug. I will fix it right away.

**Comment by jackyho112** [comment]
https://github.com/jackyho112/react-html-attributes/commit/698b0c8443ba29671237d894c44bc8ca50e1fdb0

Issue fixed. Closing.
