### ISSUE TITLE
Form doesn't support onSubmit

### ISSUE THREAD

**Issue by f-f** [jackyho112/react-html-attributes#11]
According to [React documentation](https://reactjs.org/docs/events.html#form-events), `form` elements should support the following events:
- `onChange`
- `onInput`
- `onInvalid`
- `onSubmit`

However, they don't seem to be accepted as props in the [definition of `form`](https://github.com/jackyho112/react-html-attributes/blob/master/src/react-html-attributes.json#L177)

**Comment by jackyho112** [comment]
Hey @f-f, thanks for bringing that to my attention. I will fix this as soon as I have some free time. In the meantime, feel free to submit a PR even if it's just a quick patch. 😄
