### ISSUE TITLE
Please can we have a new release, and on npm?

### ISSUE THREAD

**Issue by tesujimath** [jackyho112/react-html-attributes#14]
It seems that npm has a version 1.4.3 of this package, and it's unclear what that actually is.

Perhaps we could have a new release (>1.4.3) both here and on npm?  I am interested in recent additions, e.g. onFocus, onKeyDown, etc, which are not yet available in the released package.

**Comment by tesujimath** [comment]
@jackyho112 polite ping.  We really do need this, please!

**Comment by jackyho112** [comment]
@tesujimath I have published a new version on NPM manually, which should cover the latest changes, but I don't think I have time to do a full release here these days. Let me know if that works for now. My version of `semantic-release` is no longer supported, and that's why I can't release easily now.

**Comment by tesujimath** [comment]
@jackyho112 Ah, the version you just published doesn't seem to match the latest here, viz:
```
$ grep version node_modules/react-html-attributes/package.json 
  "version": "1.4.4"
$ grep onKeyDown node_modules/react-html-attributes/dist/react-html-attributes.json 
<no output>
```

It's the latest version of react-html-attributes.json that we really need on npm!

**Comment by tesujimath** [comment]
Plus, it would be helpful to have a tag in the git repo that matches the npm version, thanks!

**Comment by jackyho112** [comment]
@tesujimath 
Figured out the problem! Could you try again?

**Comment by tesujimath** [comment]
@jackyho112 Hmm, that still looks almost the same to me:

```
$ grep version node_modules/react-html-attributes/package.json 
    "type": "version",
  "version": "1.4.5"
$ grep -i onKeyDown node_modules/react-html-attributes/dist/react-html-attributes.json 
<still no output>
```

**Comment by jackyho112** [comment]
@tesujimath Could you try again? Sorry, I'm pretty rusty on publishing on NPM nowadays.

**Comment by tesujimath** [comment]
@jackyho112 Yep, 1.4.6 looks good now.  Thanks!!

**Comment by jackyho112** [comment]
@tesujimath Thank you for your patience!
