### ISSUE TITLE
Unnecessary test?

### ISSUE THREAD

**Issue by newyork-anthonyng** [jackyho112/react-html-attributes#4]
Thanks for the work you put into creating this project.

I was looking at the tests files and noticed one test checking if the array is alphabetically sorted. ([see here](https://github.com/jackyho112/react-html-attributes/blob/master/src/index.test.js#L27)).

Looking at the regex test we have, it looks like it's only checking that the first letter of the first element in the array is an alphabet character, or `-`.  It makes no assumptions about any of the elements actually being in alphabetical order.

For example,
```js
[
  ['carrot', 'apple', 'banana'],
  ['apple', 'carrot', 'banana'],
  ['banana', 'apple', 'carrot'],
]
// would pass your test
```
Even if the regex test did work, does the ordering of the elements matter?

**Comment by jackyho112** [comment]
The ordering of the elements doesn't really matter. But I still want them to be apathetically sorted so that it's more readable. Anyway, it's fixed and thank you again for reporting!
