### ISSUE TITLE
Incorrect email address in Code of Conduct

### ISSUE THREAD

**Issue by newyork-anthonyng** [jackyho112/react-html-attributes#5]
@jackyho112 I think you should update the [Code of Conduct](https://github.com/jackyho112/react-html-attributes/blame/master/CODE_OF_CONDUCT.md#L58) with your contact information?

**Comment by jackyho112** [comment]
@newyork-anthonyng 
Thank you so much for reporting! It's fixed now and I will look into the test one as well!
